### ISSUE TITLE
.like() Error: After filtering out keys not in the schema, your modifier is now empty

### ISSUE THREAD

**Issue by leprekon91** [copleykj/socialize-likeable#11]
Error when calling .like() on the server.
My collection:
```
export const Articles = new Mongo.Collection('articles');


Articles.schema = new SimpleSchema({
  title: { type: String },
  subtitle: { type: String },
  publishedAt: { type: Date },
  authorUID: { type: String },
  body: { type: String },
  imageUrl: { type: String },
  keywords: { type: Array },
  'keywords.$': { type: String },
});

Articles.attachSchema(Articles.schema);

export class Article extends LikeableModel(LinkParent) {}

Article.attachCollection(Articles);
LinkableModel.registerParentModel(Article);
```
Is there something else that should be done for the .like() function to work?

**Comment by leprekon91** [comment]
Okay, I attached the likeable schema: `Article.appendSchema(LikeableModel.LikeableSchema);`.
And now it works!
this should be mentioned in the readme and API.md

**Comment by leprekon91** [comment]
Also, now `.unlike()` won't work. So I just implemented a method for it that does the same. it seems to be an allow/deny thing.

**Comment by StorytellerCZ** [comment]
@leprekon91 Shouldn't it be `attachSchema`? Where are you getting the `appendSchema` function from?

**Comment by leprekon91** [comment]
I have seen an example of usage in the forums [here](https://forums.meteor.com/t/socialize-profiles/5581/2?u=andreyg) when a schema needs to be extended.
I figured since I am not switching schemas, I should use that function.
