### ISSUE TITLE
likeCount() does not increment

### ISSUE THREAD

**Issue by eladkarakuli** [copleykj/socialize-likeable#4]
After using like() on a likeableModel, and verifying that likes collection on the DB was updated, likeCount() return 0.
happens no matter how many times I've called like(), with user logged in or without.

**Comment by copleykj** [comment]
Yes, it seems I've left out the fact that you need to append the schema for LikeableModel to the model's schema.. I'm going to be reworking this package very soon to make it easier to work with.

**Comment by copleykj** [comment]
Ok, I've overhauled this so that it's a bit easier to use. Let me know if you have any trouble implementing it.

**Comment by limingth** [comment]
@copleykj  I see that recent commits has been much different from the previous release.
But I was using your code like below.  It worked with my previously defined collection posts
Now I don't know how can I do this without extend() .  I guess you should keep that flexibility. 

```
var Post = LikeableModel.extend();

// Using the previously defined collection "posts"
Posts._transform = function (document) {
   return new Post(document);
};

Post.prototype._collection = Posts;
```
