### ISSUE TITLE
A method named '/Articles/insert' is already defined

### ISSUE THREAD

**Issue by nmgwddj** [copleykj/socialize-likeable#5]
I have `Articles` collection.

```
var Likeable = BaseModel.extendAndSetupCollection("Articles");
LikeableModel.makeLikeable(Likeable, "likeable");
```

server return error: A method named '/Articles/insert' is already defined

**Comment by copleykj** [comment]
You must have already set up the collection. You can't create a Mongo.Collection twice with the same name because it creates method calls to handle client side data manipulation and you can only have one method per name.

**Comment by nmgwddj** [comment]
thanks.

**Comment by Innarticles** [comment]
I am having the same issue. I already have a collection called _Items._ How do I add likes to this model.

``` javascrip
Meteor.startup(function () {
    var Items = BaseModel.extendAndSetupCollection("items");
    LikeableModel.makeLikeable(Items, "items");
    }
  );
```

**Comment by copleykj** [comment]
The issue is being caused by the collection being created twice.
